### ISSUE TITLE
AB Benchmark: Application froze at the 65536th call.

### ISSUE THREAD

**Issue by GuneshRaj** [sdogruyol/kemal-mysql#1]
Platform: Ubuntu Linux 15 - 64bit on VirtualBox, Mysql (default 5.6), Kemal Branch, Kemal-Mysql.
Built using Crystal Build (No Release / Optimisations)

Ran a few AB test on a simple SQL Query and found that the binary froze at the 65536th call.
The call was a simple SQL statement that results in a json text.

AB commands:
ab -n 100000 -c 10 http://0.0.0.0:3000/
ab -n 100000 -c 100 http://0.0.0.0:3000/
ab -n 100000 -c 1000 http://0.0.0.0:3000/

Binary run command:
./test > test.log
tail -f test.log

Build Command:
crystal build src/test.cr

Shard file:
name: test
version: 0.1.0

authors:
- Gunesh gunesh.raj@gmail.com

license: MIT

dependencies:
  kemal:
    github: sdogruyol/kemal
    branch: master
  kemal-mysql:
    github: sdogruyol/kemal-mysql

test.cr:
require "kemal"
require "kemal-mysql"

CONN_OPTS = {
  "host" => "127.0.0.1",
  "user" => "admin",
  "password" => "admin123",
  "db" => "student"
}

mysql_connect CONN_OPTS, 25, 0.1

get "/" do |env|
  env.content_type = "application/json"
  student = conn.query("SELECT \* FROM student")
  release
  student
end

AB Results:
gunesh@gunesh-VirtualBox:~$ ab -n 100000 -c 10 http://0.0.0.0:3000/
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 0.0.0.0 (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 65536 requests completed

MySQL Stats:
Consistent in 5 open connections,
Load at 0.55-0.66
Connection and load remains the same until app is stopped.

**Comment by sdogruyol** [comment]
Whats your `ulimit -n` and connection pool size

**Comment by GuneshRaj** [comment]
ulimit -n: 1024
connection pool: default / not set.

db:student
table:student
Records:8 (id @S60, name @S255)

I am testing on a fresh Ubuntu VM, no config changes.

**Comment by GuneshRaj** [comment]
Another test was:
ab -n 65535 -c 10 http://0.0.0.0:3000/

Results:
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 0.0.0.0 (be patient)
Completed 6553 requests
Completed 13106 requests
Completed 19659 requests
Completed 26212 requests
Completed 32765 requests
Completed 39318 requests
Completed 45871 requests
Completed 52424 requests
Completed 58977 requests
Completed 65530 requests
Finished 65535 requests

Server Software:  
Server Hostname:        0.0.0.0
Server Port:            3000

Document Path:          /
Document Length:        120 bytes

Concurrency Level:      10
Time taken for tests:   21.576 seconds
Complete requests:      65535
Failed requests:        0
Total transferred:      12582720 bytes
HTML transferred:       7864200 bytes
Requests per second:    3037.37 [#/sec](mean)
Time per request:       3.292 [ms](mean)
Time per request:       0.329 [ms](mean, across all concurrent requests)
Transfer rate:          569.51 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       6
Processing:     0    3   2.1      3      24
Waiting:        0    3   2.1      3      24
Total:          0    3   2.1      3      24

Percentage of the requests served within a certain time (ms)
  50%      3
  66%      4
  75%      5
  80%      5
  90%      6
  95%      7
  98%      8
  99%     10
 100%     24 (longest request)

Then try accessing the link from the browser. It will not load. (this being the 35536th call).

Hope it helps.

**Comment by sdogruyol** [comment]
This is related to https://github.com/ysbaddaden/pool/commit/4630a55652f99a77eb3835a1afcf9d940857806f

**Comment by GuneshRaj** [comment]
Thank you, It was very helpful.

I would be working on more stress tests to validate this framework. - would
keep you posted.

regards
