### ISSUE TITLE
Crystal 0.18: Cant compile source with kemal-mysql

### ISSUE THREAD

**Issue by GuneshRaj** [sdogruyol/kemal-mysql#5]
Using the sample code as a reference, I cant seem to compile the library.

Error:

Error in ./libs/kemal-mysql/kemal-mysql.cr:25: can't use ConnectionPool(T) as the type of instance variable @mysql of Kemal::MySQL, use a more specific type

```
@mysql = ConnectionPool.new(capacity: capacity, timeout: timeout) do
```

**Comment by denpatin** [comment]
The same thing! How can this be eliminated?
<img width="797" alt="screen shot 2016-07-04 at 9 15 18 pm" src="https://cloud.githubusercontent.com/assets/1271040/16567908/a1580abe-422c-11e6-91a9-9dc63843bafc.png">

Thanks in advance!

**Comment by sdogruyol** [comment]
I just updated it to `0.3.0` https://github.com/sdogruyol/kemal-mysql/commit/6fd2c6ef0ef41447bb7ac8ec1607f97d702bd787

Can you try it?

**Comment by denpatin** [comment]
Great! Thanks, @sdogruyol! 😃
